baseURL: https://starlkyt.github.io/
title: Starlk
theme: PaperMod

languages:
  en:
    languageName: "English"

  ar:
    languageName: "العربية"
    languagedirection: rtl

params:
  displayFullLangName: true

  assets:
    favicon: "/favicon16.png"